# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email": "test@test.com",
#     "password": "test"
# }

POST http://localhost:3000/upload
Content-Type: application/json

{
    "image": "../frontend/src/imgs/404.png"
}